### ISSUE TITLE
Problems with uploading images 

### ISSUE THREAD

**Issue by VannaKarenina** [deck9/input#103]
When a user tries to add a brand image gets an error in the console:

![image](https://github.com/deck9/input/assets/46137062/bef02032-cd41-4205-b847-bf513944f2b9)

And in the docker container logs i see that app cant find storage folder 

`2023/07/24 06:37:43 [error] 16#16: *824 open() "/var/www/html/public/images/lR76/cyxlzx.1690180663.png" failed (2: No such file or directory), client: 172.17.0.1, server: _, request: "GET /images/lR76/cyxlzx.1690180663.png?w=256&q=75 HTTP/1.0", host: "domain.com", referrer: "https://domain.com/forms/lR76/settings"`

But i see that app saved image in docker volume. Maybe I didn 't set up something ?

**Comment by PhilReinking** [comment]
@VannaKarenina I will check on it later this day

**Comment by VannaKarenina** [comment]
@PhilReinking 

The domain is specified here domain.com in order not to show the real.
I started the application according to the instructions, maybe it's because I use my NGINX that is work on server ?

**Comment by PhilReinking** [comment]
ok thanks for clarification. I guess it might be possible that a symlink is not created accordingly during the image build. I will test it and let you know if I have found a fix :)

**Comment by VannaKarenina** [comment]
> @VannaKarenina I have found the issue in the nginx config we used. Thanks for bringing this to my attention, I have just pushed a fix to the codebase ([bda9ec9](https://github.com/deck9/input/commit/bda9ec9bda7fc4e5faab1dd7cee9a0e489adcb9e)) and an updated image is building right now.
> 
> Please let me know if it works for you now :)

Yeah, now images shows perfectly. Thanks ❤

But now app throw me this:
`{"message":"Cannot GET /","error":"Not Found","statusCode":404}`

**Comment by VannaKarenina** [comment]
> @VannaKarenina I have found the issue in the nginx config we used. Thanks for bringing this to my attention, I have just pushed a fix to the codebase ([bda9ec9](https://github.com/deck9/input/commit/bda9ec9bda7fc4e5faab1dd7cee9a0e489adcb9e)) and an updated image is building right now.
> 
> Please let me know if it works for you now :)

Yes, the pictures are working fine now. Thanks ❤

But i think there is another problem. App says thats we have image size limit 4BM but when i upload image with size more then 1MB we can see error:

![image](https://github.com/deck9/input/assets/46137062/83aadd56-76f3-4f40-9a53-be1e479ec404)

And console log says that:

`Failed to load resource: the server responded with a status of 413 (Request Entity Too Large)`

**Comment by PhilReinking** [comment]
@VannaKarenina thanks for another catch. Will look into that as well! :)

**Comment by PhilReinking** [comment]
okay @VannaKarenina. I found the missing config and added it to the build process.

The new release is just building, so you should be able to try out the updated image very soon.

Please let me know if it works now. This time I won't close the issue so quickly 😄

**Comment by VannaKarenina** [comment]
> okay @VannaKarenina. I found the missing config and added it to the build process.
> 
> The new release is just building, so you should be able to try out the updated image very soon.
> 
> Please let me know if it works now. This time I won't close the issue so quickly 😄

@PhilReinking tested new build.

Everything works fine. Thanks ❤

If I find something else, I will open a new issue :)
