### ISSUE TITLE
Some encoding problems and field names in csv

### ISSUE THREAD

**Issue by VannaKarenina** [deck9/input#107]
Hi guys.

Found a problem with exporting data to CSV. Some answers in other languages are exported in this format:
![image](https://github.com/deck9/input/assets/46137062/35ceb5a1-e555-4765-a57c-d1cc23024080)

And I have another question. Is it possible to make a normal display of the question instead of symbols as in the screenshot ?

**Comment by PhilReinking** [comment]
Hey @VannaKarenina, thx for reporting. I will hava look into this. Can you tell me what language you used?

To your other question, right now you can only change the "title" of a block. You can find that in the editor via block settings. The title should also be used for the export column names.

**Comment by VannaKarenina** [comment]
> Hey @VannaKarenina, thx for reporting. I will hava look into this. Can you tell me what language you used?
> 
> To your other question, right now you can only change the "title" of a block. You can find that in the editor via block settings. The title should also be used for the export column names.

Some of the respondents answered in Chinese, Russian, Japanese, Korean.

Tried set title of a block and in settings i have this:
![image](https://github.com/deck9/input/assets/46137062/26c45482-db2c-478f-a1da-e8126280bf97)
And still have name of the qustion like id:
![image](https://github.com/deck9/input/assets/46137062/c7b98924-804f-4c66-a114-5ecbbd3c11f1)
