### ISSUE TITLE
User management controls for self hosted

### ISSUE THREAD

**Issue by TheElite96** [deck9/input#119]
As was mentioned in #99 by @PhilReinking,
> Also I'm thinking that it might be nice to enable team accounts on the self-hosted version. It would enable teams to give individual users their own credentials to access forms.
> Can you tell me if this would match your expectations of an onboarding more then what we have now?

I fully support this but I'm going to expand on that thought with my own suggestion. I would like to see the ability on the self hosted version for accounts to be labeled as site admins, and for those admins to have the ability to do things like, for example, disable new user signups, or regulate user permissions. (For example, permissions specific to making forms, viewing results, etc.).

Case example for this being useful is my own use of Input. I am planning on potentially using Input for feedback surveys in a large online community. As you may understand, I do not want random users signing up to create their own forms as that is not the purpose of the site.

Hope that makes sense.

**Comment by PhilReinking** [comment]
@TheElite96 yes that makes sense.

I was considering changing the self-hosted version to allow having only one team per instance. And then, as an admin, you would be able to add / remove additional members and maybe use roles in the future to give your team members different permissions on your forms.

I think this might be a better model than the current one, since the self-hosted version is intended for individuals and businesses that use the software for themselves, so there should no need to have multiple separate teams.

Would this suite your own use case to use Input?

**Comment by TheElite96** [comment]
Yes that would definitely be a better model than the current one for self-hosted, for the reasons you stated, and it would absolutely suite my use case of it. I'm sure it would benefit others too. The single team per instance sounds good and having roles within that team later down the line would potentially be a good addition too.

**Comment by PhilReinking** [comment]
Thanks for the feedback. I will put it on the backlog for the next release. Can't give a timeline right now, but think I can do it in the upcoming week.

**Comment by vlude** [comment]
Is there currently a method to disable registration? As previously mentioned, I do not want that everyone can sign-up and create forms

**Comment by PhilReinking** [comment]
@vlude unfortunately no, but I intend to release the switch to the team model by the end of this year.

**Comment by PhilReinking** [comment]
@TheElite96 @vlude Team Based Architecture is now available in v1.8.0

**Comment by Basserado** [comment]
There is still no switch for deactivating the registration or have I overlooked it?

**Comment by PhilReinking** [comment]
@Basserado you are right. I will add this as soon as possible!

**Comment by PhilReinking** [comment]
@Basserado You are right. But you can now only have one team on your instance. So if you are the first user, all other users can use the app only by invite.

I will add the option to disable the registration page in the future, as soon as I can fit it in :)
