### ISSUE TITLE
I'm not recieving team invitation mails!

### ISSUE THREAD

**Issue by dataprolet** [deck9/input#133]
I'm [running Input behind a reverse proxy using docker](https://github.com/deck9/input?tab=readme-ov-file#behind-a-proxy), but I can't invite other members to join my team, because they don't receive the invitation e-mail.

The container's log is showing that a mail was sent, but I never received it. Do I have to manually set up a mail server or is this intended to work out-of-the-box?

**Comment by PhilReinking** [comment]
Hey @dataprolet 

Sorry, this is right now not documented well enough. You need to provide your own SMTP service to send emails.

Currently, these are the environment variables used for this:

```
### Mail Config
# MAIL_MAILER=smtp
# MAIL_HOST=
# MAIL_USERNAME=
# MAIL_PASSWORD=
# MAIL_PORT=1025
# MAIL_ENCRYPTION=tls
```

You can find more settings in the [.env.prod.example](https://github.com/deck9/input/blob/main/.env.prod.example) file.

Please let me know if this solves the issue for you!

**Comment by dataprolet** [comment]
Thanks, will try.
