### ISSUE TITLE
Configure multiple questions on a single page

### ISSUE THREAD

**Issue by jessestippel** [deck9/input#138]
Configuring whether or not a group displays all blocks within it, would be incredibly useful for non survey related forms.

* When creating a group, implement a toggle to display all questions within said group.

**Comment by PhilReinking** [comment]
duplicate of #105 

we are still figuring out how to do it. As of today I am not even sure if similar tools like Typeform are doing this. If you have any other input on that, I will be grateful if you point me in the right direction :)
