### ISSUE TITLE
[bug] Export/Import or Duplicate Form

### ISSUE THREAD

**Issue by shurco** [deck9/input#148]
Input - latest version.
When attempting to duplicate a form or during Import/Export, fields located in a group are not transferred.

The survey that I am exporting or trying to duplicate:
<img width="946" alt="original" src="https://github.com/deck9/input/assets/411055/ff64b239-61dc-40d2-9c87-d0d1d4d164c6">

Result after importing or duplicating the survey:
<img width="946" alt="duplicate" src="https://github.com/deck9/input/assets/411055/22ee10ed-bdc7-42b5-8e97-a023648beb45">

**Comment by PhilReinking** [comment]
fixed in #163
