### ISSUE TITLE
Bug related to consent type

### ISSUE THREAD

**Issue by 0xAndrewBlack** [deck9/input#157]
Steps to reproduce:
1. Fresh install of input
2. Create a form with a consent block somewhere (it does not matter where specifically)
3. Publish it
4. When clicking the progress arrows back you can only go back one step then the stepper will disappear
5. Click submit for the current answer and you can go along the stepper will appear again
6. Go back to step 4 this bug will haunt the form...

Trace:
![image](https://github.com/deck9/input/assets/50300348/4fdbd19f-14af-4968-b154-90e5f78f1e4f)
![image](https://github.com/deck9/input/assets/50300348/019811d5-1c27-4f8a-8144-b14c55740371)

**Comment by PhilReinking** [comment]
@0xAndrewBlack could not reproduce it. can you check again if this is happening for you in the latetest release?
