### ISSUE TITLE
No Feedback When Password Is Incorrect

### ISSUE THREAD

**Issue by fmunim** [deck9/input#158]
https://github.com/deck9/input/assets/32178410/c6331bd7-61e9-4e8f-920f-077b47edc988

**Comment by PhilReinking** [comment]
@fmunim you should get a feedback for the password form. Maybe there is another issue with your configuration setup. Is there anything you see in the network request or the server logs?

**Comment by PhilReinking** [comment]
This has now been fixed in latest release
