### ISSUE TITLE
Some users confused by file upload

### ISSUE THREAD

**Issue by TheRouce** [deck9/input#169]
I've gotten a number of user reports that they are unable to upload files because on mobile some don't understand that you're supposed to tap on the text and not in the surrounding dotted box. 

I would suggest either making the entire file upload element a button, or by creating a separate element similar to this mockup
![image](https://github.com/user-attachments/assets/10b2b870-bd8a-4572-b94d-cc1c61d8f6fc)

**Comment by TheRouce** [comment]
I'd be happy to put in a PR, though I am currently unfamiliar with the codebase.

**Comment by PhilReinking** [comment]
@TheRouce thanks for the feedback. I will make some tests and try to fix it.

**Comment by PhilReinking** [comment]
@TheRouce fixed it by making the whole area clickable for mobile users.
Also removed the drop zone keyword, since this will not work on mobile anyways.

![CleanShot 2024-09-13 at 11 59 28](https://github.com/user-attachments/assets/5433142d-68eb-4a06-ab71-fb2e14b3fca1)
