### ISSUE TITLE
Default credentials?

### ISSUE THREAD

**Issue by danielslyman** [deck9/input#99]
Hello,

I am up and running, I didn't find any default credentials so I registered. However, upon trying to create a new form, the browser console displays an unauthorized error. Additionally, how do I prevent user signups?

Best,
Daniel

**Comment by PhilReinking** [comment]
Hey @danielslyman,

thx for mentioning that. For now I did not consider this (like registering as a new user) to be a problem. Thinking over it, it might be a nice improvement for the self-hosted version to have an onboarding experience, where you just get to a "Create your first user" screen.

Also I'm thinking that it might be nice to enable team accounts on the self-hosted version. It would enable teams to give individual users their own credentials to access forms.

Can you tell me if this would match your expectations of an onboarding more then what we have now?

**Comment by sollerd** [comment]
Hi @danielslyman following up on this, I get the same problem. I was able to create a new account by using the registration process. However, when I try to create a new form, nothing happens. Looking into the network tab, I can see the request fails with 401 Unauthorized.

Im using the docker build.

**Comment by PhilReinking** [comment]
@sollerd thx for confirming. I will take a look at it as soon as possible. Have you tried to access it via `localhost` or did you set up a proxy in front of the container?

**Comment by sollerd** [comment]
@PhilReinking I used nginx as reverse proxy and proper sub domain and letsencrypt setup

**Comment by PhilReinking** [comment]
@sollerd, have you configured the `APP_URL` env to contain the URL you use to access the app? I am trying to replicate your issue right now, and I think that might be the most obvious thing going wrong here.

If this solves the issue, I need to add documentation on how to configure the app to use with a proxy.

**Comment by PhilReinking** [comment]
@sollerd @danielslyman I have added instructions for a setup behind a proxy to the [Readme](https://github.com/deck9/input#behind-a-proxy).

**Comment by danielslyman** [comment]
Thanks for helping, I'll look into it :)
